### ISSUE TITLE
Unexpected EOF while extracting mainnet snapshot

### ISSUE THREAD

**Issue by ozgrakkurt** [bnb-chain/opbnb-snapshot#5]
I get this error every time I try to extract the downloaded archive using a command like this:

```
wget -q -O - https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20240208.tar.gz | tar -zxvf -
```

```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
````

The error happens when extracted data reaches about 1.1TB

Also tried first fully downloading and then extracting

**Comment by royceroyceroyce** [comment]
Please try our latest snapshot 
https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20240215.tar.gz

Meanwhile, we are also generating a new snapshot

**Comment by roycncn** [comment]
root@vmi1668770:/data# wget -c https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20240215.tar.gz -O - | tar -xz
--2024-02-20 09:20:38--  https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20240215.tar.gz
Resolving tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com (tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com)... 52.219.8.63, 52.219.150.26, 3.5.155.125, ...
Connecting to tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com (tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com)|52.219.8.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 915148251136 (852G) [application/x-tar]
Saving to: ‘STDOUT’

-                                                7%[======>                                                                       -                                100%[========================================================>] 852.30G  34.2MB/s    in 7h 26m

2024-02-20 16:46:55 (32.6 MB/s) - written to stdout [915148251136/915148251136]


gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by roycncn** [comment]
no luck

**Comment by royceshen** [comment]
looks like our snapshot pipeline is broken, we will fix it as soon as possible.

**Comment by royceroyceroyce** [comment]
Looks like our snapshot pipeline is broken, we will fix it asap

**Comment by royceshen** [comment]
https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20240220.tar.gz
For the moment, we've generated a pruned snapshot as a workaround. But please note that the pruned snapshot has erased state data before block height: 16319074.

We are still fixing the archive snapshot and will upload it once ready.

**Comment by royceroyceroyce** [comment]
https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20240220.tar.gz
For the moment, we've generated a pruned snapshot as a workaround. But please note that the pruned snapshot has erased state data before block height: 16319074.

We are still fixing the archive snapshot and will upload it once ready.

**Comment by ozgrakkurt** [comment]
> https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20240220.tar.gz For the moment, we've generated a pruned snapshot as a workaround. But please note that the pruned snapshot has erased state data before block height: 16319074.
> 
> We are still fixing the archive snapshot and will upload it once ready.

Hey, thanks for fixing this! Is there any update about the archival snapshot?

**Comment by owen-reorg** [comment]
All current links work.

```
$ http --head https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20240229.tar.gz
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 2114038780581
Content-Type: application/x-tar
Date: Tue, 05 Mar 2024 07:42:46 GMT
ETag: "3885d192c0d636038cc4b4b45228cb97-7876"
Last-Modified: Sat, 02 Mar 2024 18:45:46 GMT
Server: AmazonS3
x-amz-expiration: expiry-date="Tue, 02 Apr 2024 00:00:00 GMT", rule-id="default"
x-amz-id-2: 1WjBOqHnU2M4NZd5QnmBSS9iuY3kIODm/2xB6YUB4YqpxpA0BWgC6wRwmPKZRj5EQSsdLhtN25g=
x-amz-request-id: KM9RPCDN0A0P9FGH
x-amz-server-side-encryption: AES256


$ http --head https://tf-bnbchain-prod-opbnb-mainnet-snapshot-s3-ap-northeast-1.s3.ap-northeast-1.amazonaws.com/geth-20240220.tar.gz

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 215477368660
Content-Type: application/x-tar
Date: Tue, 05 Mar 2024 07:42:56 GMT
ETag: "d3421c6f75f3710e6d4d584dde0d4c25-6422"
Last-Modified: Wed, 21 Feb 2024 03:24:37 GMT
Server: AmazonS3
x-amz-expiration: expiry-date="Sat, 23 Mar 2024 00:00:00 GMT", rule-id="default"
x-amz-id-2: jNsG+4C2RkVRXi+m2IKWU2ciIKHjyoYlnUi3nNDMu6P448VFSCoE26TJQeeH1jvJ9y29uCYY238=
x-amz-request-id: T4EZPB2PVXDRD9RS
x-amz-server-side-encryption: AES256


$ http --head https://tf-nodereal-prod-opbnb-testnet-snapshot-s3-ap.s3.ap-northeast-1.amazonaws.com/geth-20240229.tar.gz


HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 490767697840
Content-Type: application/x-tar
Date: Tue, 05 Mar 2024 07:43:13 GMT
ETag: "48483e49d3f8f4d3605006811e3903e8-7314"
Last-Modified: Thu, 29 Feb 2024 14:35:54 GMT
Server: AmazonS3
x-amz-expiration: expiry-date="Fri, 08 Mar 2024 00:00:00 GMT", rule-id="default"
x-amz-id-2: rG9+NTrD32D9c7JTp12+nxxBQfEBt5JgL9DuuZX54+dn6TCpL7tLCWElZeefTW2Bh0OaFGVkam0=
x-amz-request-id: RBAC8SFWGS61S07J
x-amz-server-side-encryption: AES256
```
